# Generated by Django 5.2.7 on 2025-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('times_quizzed', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0)),
            ],
        ),
    ]
