# Generated by Django 5.2.7 on 2025-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_customquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('uk', 'Ukrainian'), ('pl', 'Polish'), ('fr', 'French'), ('es', 'Spanish')], default='de', max_length=5),
        ),
    ]
