# Generated by Django 5.2.7 on 2025-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_customquiz_owner_word_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_quizable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('uk', 'Ukrainian'), ('pl', 'Polish'), ('fr', 'French'), ('es', 'Spanish')], default='de', max_length=5),
        ),
    ]
